services:
  - type: web
    name: cinestelar-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server_clean.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
